#!/usr/bin/env python3
"""
Create a matplotlib radial chart of hand counts by num_players.

By default this reads the CSV generated by create_num_players_radial_chart.py
and writes a PNG chart. Pass an SVG path with --svg-output to also save a
vector copy.
"""

from __future__ import annotations

import argparse
import csv
import os
from pathlib import Path
from typing import NamedTuple


os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib.patches import Patch


COLORS = [
    "#2563eb",
    "#16a34a",
    "#dc2626",
    "#9333ea",
    "#ea580c",
    "#0891b2",
    "#4f46e5",
    "#65a30d",
    "#be123c",
    "#7c3aed",
    "#0d9488",
    "#ca8a04",
]


class Row(NamedTuple):
    num_players: int
    hands: int
    percent: float


def read_rows(csv_path: Path) -> list[Row]:
    rows: list[Row] = []
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(
                Row(
                    num_players=int(row["num_players"]),
                    hands=int(row["hands"]),
                    percent=float(row["percent"]),
                )
            )
    return rows


def format_int(value: int) -> str:
    return f"{value:,}"


def autopct(percent: float) -> str:
    return f"{percent:.1f}%" if percent >= 1.5 else ""


def plot_chart(rows: list[Row], output_path: Path, source_path: Path) -> None:
    total = sum(row.hands for row in rows)
    labels = [f"{row.num_players}p" for row in rows]
    values = [row.hands for row in rows]
    colors = COLORS[: len(rows)]

    fig, ax = plt.subplots(figsize=(12, 8), facecolor="#f8fafc")
    ax.set_facecolor("#f8fafc")

    wedges, _, autotexts = ax.pie(
        values,
        labels=labels,
        colors=colors,
        startangle=90,
        counterclock=False,
        autopct=autopct,
        pctdistance=0.82,
        labeldistance=1.08,
        wedgeprops={"width": 0.42, "edgecolor": "white", "linewidth": 2},
        textprops={"color": "#374151", "fontsize": 11, "fontweight": "semibold"},
    )

    for text in autotexts:
        text.set_color("#111827")
        text.set_fontsize(10)
        text.set_fontweight("bold")

    ax.text(
        0,
        0.06,
        format_int(total),
        ha="center",
        va="center",
        fontsize=25,
        fontweight="bold",
        color="#111827",
    )
    ax.text(
        0,
        -0.12,
        "Total Hands",
        ha="center",
        va="center",
        fontsize=10,
        fontweight="bold",
        color="#6b7280",
    )

    legend_handles = [Patch(facecolor=color, edgecolor="none") for color in colors]
    legend_labels = [
        f"{row.num_players} players  {format_int(row.hands)} ({row.percent:.2f}%)"
        for row in rows
    ]
    ax.legend(
        legend_handles,
        legend_labels,
        title="num_players",
        loc="center left",
        bbox_to_anchor=(1.02, 0.5),
        frameon=False,
        fontsize=10,
        title_fontsize=12,
    )

    ax.set_title(
        "Hand Composition by Number of Players",
        loc="left",
        fontsize=20,
        fontweight="bold",
        color="#111827",
        pad=22,
    )
    fig.text(
        0.125,
        0.89,
        "Distribution of cleaned poker hands grouped by num_players",
        fontsize=11,
        color="#4b5563",
    )
    fig.text(0.125, 0.04, f"Source: {source_path}", fontsize=8, color="#6b7280")

    ax.set(aspect="equal")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=180, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "csv",
        type=Path,
        nargs="?",
        default=Path("processed/nolimit_holdem/num_players_radial_chart.csv"),
        help="CSV containing num_players,hands,percent",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("processed/nolimit_holdem/num_players_radial_chart_matplotlib.png"),
        help="PNG output path",
    )
    parser.add_argument(
        "--svg-output",
        type=Path,
        default=Path("processed/nolimit_holdem/num_players_radial_chart_matplotlib.svg"),
        help="Optional SVG output path. Use an empty string to skip.",
    )
    args = parser.parse_args()

    csv_path = args.csv.resolve()
    output_path = args.output.resolve()
    if not csv_path.is_file():
        raise SystemExit(f"Not a file: {csv_path}")

    rows = read_rows(csv_path)
    plot_chart(rows, output_path, csv_path)
    print(f"chart,{output_path}")

    if str(args.svg_output):
        svg_output_path = args.svg_output.resolve()
        plot_chart(rows, svg_output_path, csv_path)
        print(f"svg_chart,{svg_output_path}")

    print(f"hands,{sum(row.hands for row in rows)}")


if __name__ == "__main__":
    main()
